Cloud testapp
Otus-DevOps-2023-03/Romand2_infra pull request #3
Opened 2023-05-04 15:30 UTC by Romand2

# Выполнено ДЗ №4

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Cоздан instance
 - Созданы скрипты для установки и деплоя 
 - Создан общий скрипт, позволяющий установить инстанс и зависимости для приложения

## Как запустить проект:
 - Выполнить комнаду start.sh

## Как проверить работоспособность:
 - Например, перейти по ссылке http://51.250.70.109:9292/login

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-05-05 10:24 UTC, Romand2 commented
@mrgreyves, Добрый день, подскажите, что делать с этими тестами, со стороны ВМ все прекрасно работает, не понимаю в чем может быть проблема в тестах с запуском сервера.

2023-05-05 13:32 UTC, mrgreyves requested changes
Здравствуйте!
![image](https://user-images.githubusercontent.com/34331259/236471551-78e77c86-4552-48c8-9ce9-72359d6eaf92.png)
У вас проблемы со скриптами
Для начала сделайте их исполняемыми и проверьте

2023-05-05 15:44 UTC, Romand2 commented
@mrgreyves , они исполняемые , сделал chmod +x, добавил , заеомиттил и запушил

2023-05-10 07:47 UTC, Romand2 commented
@mrgreyves 
![image](https://github.com/Otus-DevOps-2023-03/Romand2_infra/assets/58710885/a1bc5d65-df32-4290-9a4f-b65594610ae6)

2023-05-10 07:55 UTC, Romand2 commented
@mrgreyves , пофиксил, проверьте пожалуйста:)

2023-05-10 20:48 UTC, mrgreyves approved these changes
Здравствуйте!)
Вижу что вам удалось все починить, хорошая работа =)

2023-05-11 09:00 UTC, merged